- Implemented calculation sum with `ExecutorService`
Likh-Alex/concurrency pull request #2
Opened 2021-02-23 18:39 UTC by Likh-Alex

- Implemented calculation sum with `ForkJoin`
- Written simple tests

2021-02-23 19:29 UTC, Ketch92 approved these changes
Well done

2021-02-23 19:29 UTC, Ketch92 commented on src/main/java/processing/SumListWithCallable.java
> +    }
Ти можеш замінити весь цей метод на один стрім

2021-02-23 19:41 UTC, Likh-Alex commented on src/main/java/processing/SumListWithCallable.java
> +    }
заменил - выглядит короче) Спасибо

2021-02-24 12:06 UTC, Sofasmile requested changes

2021-02-24 12:06 UTC, Sofasmile commented on src/main/java/thread/CallableThread.java
> +public class CallableThread implements Callable<Integer> {
```suggestion
public class SumCalculatorCallable implements Callable<Integer> {
```

2021-02-24 12:06 UTC, Sofasmile commented on src/main/java/thread/RecursiveTaskThread.java
> +public class RecursiveTaskThread extends RecursiveTask<Integer> {
```suggestion
public class SumCalculatorRecursiveTask extends RecursiveTask<Integer> {
```

2021-02-24 12:06 UTC, Sofasmile commented on src/main/java/util/Util.java
> +public class Util {
```suggestion
public class ListOfNumbersCreator/ListOfNumbersGenerator {
```

2021-02-24 12:06 UTC, Sofasmile commented on src/main/java/util/Util.java
> +    public int getCurrentSum() {
цей метод ми використовуємо лише в тестах, тому пропоную винести його з цього класу туди

2021-02-24 12:06 UTC, Sofasmile commented on src/main/java/util/Util.java
> +    private final List<Integer> list = new ArrayList<>();
спробуй перенести це поле в метод, де це потрібно. Тоді наш клас буде stateless

2021-02-24 12:06 UTC, Sofasmile commented on src/test/java/SumListWithCallableTest.java
> +import static org.junit.Assert.*;
автоімпорти злоо - старайся їх не використовувати

2021-02-24 12:06 UTC, Sofasmile commented on src/test/java/SumListWithCallableTest.java
> +    private static Util util;
чому ці змінні статичні?

2021-02-24 12:06 UTC, Sofasmile commented on src/test/java/SumListWithCallableTest.java
> +}
пуста строка

2021-02-24 12:06 UTC, Sofasmile commented on src/test/java/SumListWithCallableTest.java
> +    public void getSummary_Ok() {
загалом одного тесту замало, але для даного завдання можеш залишити як є

2021-02-24 12:06 UTC, Sofasmile commented on src/test/java/SumListWithForkJoinTest.java
> +}
пуста строка

2021-02-24 14:12 UTC, Likh-Alex commented on src/main/java/thread/CallableThread.java
> +public class CallableThread implements Callable<Integer> {
Done, thank you

2021-02-24 14:12 UTC, Likh-Alex commented on src/main/java/thread/RecursiveTaskThread.java
> +public class RecursiveTaskThread extends RecursiveTask<Integer> {
Done, thank you

2021-02-24 14:20 UTC, Likh-Alex commented on src/main/java/util/Util.java
> +    public int getCurrentSum() {
moved this method to the tests

2021-02-24 14:20 UTC, Likh-Alex commented on src/main/java/util/Util.java
> +public class Util {
Done

2021-02-24 14:24 UTC, Likh-Alex commented on src/main/java/util/Util.java
> +    private final List<Integer> list = new ArrayList<>();
Перенёс везде где вызывается `getRandomList` и передаю в него же

2021-02-24 14:26 UTC, Likh-Alex commented on src/test/java/SumListWithCallableTest.java
> +import static org.junit.Assert.*;
есть за мной такой грешок, поправил везде где был автоимпорт со звёздочкой

2021-02-24 14:27 UTC, Likh-Alex commented on src/test/java/SumListWithCallableTest.java
> +    private static Util util;
Потому что я забыл их правильно объявить) Убрал

2021-02-24 14:29 UTC, Likh-Alex commented on src/test/java/SumListWithCallableTest.java
> +}
добавил... -_-

2021-02-24 14:29 UTC, Likh-Alex commented on src/test/java/SumListWithCallableTest.java
> +    public void getSummary_Ok() {
Понял, спасибо)

2021-02-24 14:29 UTC, Likh-Alex commented on src/test/java/SumListWithForkJoinTest.java
> +}
Теперь есть)

2021-02-24 14:54 UTC, Sofasmile approved these changes

2021-02-28 16:07 UTC, merged